### ISSUE TITLE
batch: 'visible' field in share an event

### ISSUE THREAD

**Issue by vinibgoulart** [event-list/event-list#185]
Batches in event should be visible or not

if a batch isnt visible, only the merchant will can add participants on this batch

create a new field inpuCheckbox that define it

![image](https://user-images.githubusercontent.com/88122830/228704794-cf55d6c7-db54-405a-bbef-b51334d791d0.png)

**Comment by daniloab** [comment]
is this complex? what can you simplify?

**Comment by vinibgoulart** [comment]
closed #261
